theme: jekyll-theme-minimal
title: "nikander100"
description: "My personal website!"

search_enabled: true
heading_anchors: true
color_scheme: dark
# ga_tracking:

# Aux links for the upper right navigation
aux_links:
  "my github":
    - "//github.com/nikander100"